CREATE TABLE `genome_mapping` (
  `id` INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `name` VARCHAR(256) NOT NULL
);

INSERT INTO genome_mapping(name) VALUES ('Contemplative');
INSERT INTO genome_mapping(name) VALUES ('Feel Good');
INSERT INTO genome_mapping(name) VALUES ('Follow Your Dream');
INSERT INTO genome_mapping(name) VALUES ('Self Discovery');
INSERT INTO genome_mapping(name) VALUES ('Ambition');
INSERT INTO genome_mapping(name) VALUES ('Hopes');
INSERT INTO genome_mapping(name) VALUES ('Mind and Soul');
INSERT INTO genome_mapping(name) VALUES ('Introspection');
INSERT INTO genome_mapping(name) VALUES ('Way of Life');
INSERT INTO genome_mapping(name) VALUES ('Society');
INSERT INTO genome_mapping(name) VALUES ('Documentary');
INSERT INTO genome_mapping(name) VALUES ('Contemporary');
INSERT INTO genome_mapping(name) VALUES ('21st Century');
INSERT INTO genome_mapping(name) VALUES ('Reenactment');
INSERT INTO genome_mapping(name) VALUES ('Serious');
INSERT INTO genome_mapping(name) VALUES ('Slow');
INSERT INTO genome_mapping(name) VALUES ('Atmospheric');
INSERT INTO genome_mapping(name) VALUES ('Music Band');
INSERT INTO genome_mapping(name) VALUES ('Partners');
INSERT INTO genome_mapping(name) VALUES ('Buddies');
INSERT INTO genome_mapping(name) VALUES ('Musician''s Life');
INSERT INTO genome_mapping(name) VALUES ('Performer''s Life');
INSERT INTO genome_mapping(name) VALUES ('Showbiz');
INSERT INTO genome_mapping(name) VALUES ('Artists and Showbiz');
INSERT INTO genome_mapping(name) VALUES ('Music');
INSERT INTO genome_mapping(name) VALUES ('Music Concert');
INSERT INTO genome_mapping(name) VALUES ('England');
INSERT INTO genome_mapping(name) VALUES ('Europe');
INSERT INTO genome_mapping(name) VALUES ('Realistic');
INSERT INTO genome_mapping(name) VALUES ('Electronica');
INSERT INTO genome_mapping(name) VALUES ('Pop');
INSERT INTO genome_mapping(name) VALUES ('Suspenseful');
INSERT INTO genome_mapping(name) VALUES ('Murder');
INSERT INTO genome_mapping(name) VALUES ('Police Investigation');
INSERT INTO genome_mapping(name) VALUES ('Crimes');
INSERT INTO genome_mapping(name) VALUES ('Deadly');
INSERT INTO genome_mapping(name) VALUES ('Dishonesty');
INSERT INTO genome_mapping(name) VALUES ('Law Enforcement');
INSERT INTO genome_mapping(name) VALUES ('Family Relations');
INSERT INTO genome_mapping(name) VALUES ('Siblings Relations');
INSERT INTO genome_mapping(name) VALUES ('Small Town Life');
INSERT INTO genome_mapping(name) VALUES ('Police Detective');
INSERT INTO genome_mapping(name) VALUES ('Crime');
INSERT INTO genome_mapping(name) VALUES ('Thriller');
INSERT INTO genome_mapping(name) VALUES ('20th Century');
INSERT INTO genome_mapping(name) VALUES ('90s');
INSERT INTO genome_mapping(name) VALUES ('Alabama');
INSERT INTO genome_mapping(name) VALUES ('USA');
INSERT INTO genome_mapping(name) VALUES ('Small Town');
INSERT INTO genome_mapping(name) VALUES ('Based on True Story');
INSERT INTO genome_mapping(name) VALUES ('Humorous');
INSERT INTO genome_mapping(name) VALUES ('Anti Heroes');
INSERT INTO genome_mapping(name) VALUES ('Heroic Mission');
INSERT INTO genome_mapping(name) VALUES ('Mistaken Identity');
INSERT INTO genome_mapping(name) VALUES ('Heroes');
INSERT INTO genome_mapping(name) VALUES ('Misfit');
INSERT INTO genome_mapping(name) VALUES ('Save the Day');
INSERT INTO genome_mapping(name) VALUES ('Against the Odds');
INSERT INTO genome_mapping(name) VALUES ('Danger');
INSERT INTO genome_mapping(name) VALUES ('Rivalry');
INSERT INTO genome_mapping(name) VALUES ('Action');
INSERT INTO genome_mapping(name) VALUES ('Comedy');
INSERT INTO genome_mapping(name) VALUES ('Musical');
INSERT INTO genome_mapping(name) VALUES ('Foreign');
INSERT INTO genome_mapping(name) VALUES ('Bollywood');
INSERT INTO genome_mapping(name) VALUES ('Martial Arts');
INSERT INTO genome_mapping(name) VALUES ('Asia');
INSERT INTO genome_mapping(name) VALUES ('China');
INSERT INTO genome_mapping(name) VALUES ('India');
INSERT INTO genome_mapping(name) VALUES ('Teens');
INSERT INTO genome_mapping(name) VALUES ('Semi Serious');
INSERT INTO genome_mapping(name) VALUES ('Indian');
INSERT INTO genome_mapping(name) VALUES ('Mild Violent Content');
INSERT INTO genome_mapping(name) VALUES ('Bleak');
INSERT INTO genome_mapping(name) VALUES ('Tense');
INSERT INTO genome_mapping(name) VALUES ('Gloomy');
INSERT INTO genome_mapping(name) VALUES ('Rough');
INSERT INTO genome_mapping(name) VALUES ('Vengeance');
INSERT INTO genome_mapping(name) VALUES ('Parents and Children');
INSERT INTO genome_mapping(name) VALUES ('Dysfunctional Family');
INSERT INTO genome_mapping(name) VALUES ('Family in Crisis');
INSERT INTO genome_mapping(name) VALUES ('Estrangement');
INSERT INTO genome_mapping(name) VALUES ('Family Problems');
INSERT INTO genome_mapping(name) VALUES ('Betrayal');
INSERT INTO genome_mapping(name) VALUES ('Psychological');
INSERT INTO genome_mapping(name) VALUES ('Drama');
INSERT INTO genome_mapping(name) VALUES ('Film Noir');
INSERT INTO genome_mapping(name) VALUES ('40s');
INSERT INTO genome_mapping(name) VALUES ('New York');
INSERT INTO genome_mapping(name) VALUES ('Prison');
INSERT INTO genome_mapping(name) VALUES ('Award Winner');
INSERT INTO genome_mapping(name) VALUES ('Prestigious Awards');
INSERT INTO genome_mapping(name) VALUES ('Cannes Festival Winner');
INSERT INTO genome_mapping(name) VALUES ('Based on Book');
INSERT INTO genome_mapping(name) VALUES ('B&amp;W');
INSERT INTO genome_mapping(name) VALUES ('A.I.');
INSERT INTO genome_mapping(name) VALUES ('Benign Alien');
INSERT INTO genome_mapping(name) VALUES ('Race Against Time');
INSERT INTO genome_mapping(name) VALUES ('Save the World');
INSERT INTO genome_mapping(name) VALUES ('Alien Encounter');
INSERT INTO genome_mapping(name) VALUES ('Apocalypse');
INSERT INTO genome_mapping(name) VALUES ('Disaster');
INSERT INTO genome_mapping(name) VALUES ('Future Dystopia');
INSERT INTO genome_mapping(name) VALUES ('Space Travel');
INSERT INTO genome_mapping(name) VALUES ('Time Travel');
INSERT INTO genome_mapping(name) VALUES ('Chases and Races');
INSERT INTO genome_mapping(name) VALUES ('Space and Aliens');
INSERT INTO genome_mapping(name) VALUES ('Escapades');
INSERT INTO genome_mapping(name) VALUES ('Imaginary');
INSERT INTO genome_mapping(name) VALUES ('Chaos');
INSERT INTO genome_mapping(name) VALUES ('Evil Alien');
INSERT INTO genome_mapping(name) VALUES ('Pregnancy');
INSERT INTO genome_mapping(name) VALUES ('Supernatural');
INSERT INTO genome_mapping(name) VALUES ('Sci-Fi');
INSERT INTO genome_mapping(name) VALUES ('Adventure');
INSERT INTO genome_mapping(name) VALUES ('Fantasy');
INSERT INTO genome_mapping(name) VALUES ('Horror');
INSERT INTO genome_mapping(name) VALUES ('Himalaya');
INSERT INTO genome_mapping(name) VALUES ('Boys'' Night');
INSERT INTO genome_mapping(name) VALUES ('Fantastic');
INSERT INTO genome_mapping(name) VALUES ('Fast');
INSERT INTO genome_mapping(name) VALUES ('Bounty Hunter');
INSERT INTO genome_mapping(name) VALUES ('On the Run');
INSERT INTO genome_mapping(name) VALUES ('Track Down');
INSERT INTO genome_mapping(name) VALUES ('Criminal Heroes');
INSERT INTO genome_mapping(name) VALUES ('Gang');
INSERT INTO genome_mapping(name) VALUES ('Lovers on the Run');
INSERT INTO genome_mapping(name) VALUES ('Rescue');
INSERT INTO genome_mapping(name) VALUES ('Cons and Scams');
INSERT INTO genome_mapping(name) VALUES ('Heist');
INSERT INTO genome_mapping(name) VALUES ('Kidnapping');
INSERT INTO genome_mapping(name) VALUES ('Woman in Danger');
INSERT INTO genome_mapping(name) VALUES ('80s');
INSERT INTO genome_mapping(name) VALUES ('Silly Humor');
INSERT INTO genome_mapping(name) VALUES ('On the Road');
INSERT INTO genome_mapping(name) VALUES ('Thought Provoking');
INSERT INTO genome_mapping(name) VALUES ('Human Nature');
INSERT INTO genome_mapping(name) VALUES ('Social Decay');
INSERT INTO genome_mapping(name) VALUES ('Life is a Bitch');
INSERT INTO genome_mapping(name) VALUES ('Soldier');
INSERT INTO genome_mapping(name) VALUES ('Military Life');
INSERT INTO genome_mapping(name) VALUES ('Military');
INSERT INTO genome_mapping(name) VALUES ('Power Relations');
INSERT INTO genome_mapping(name) VALUES ('Russia');
INSERT INTO genome_mapping(name) VALUES ('Urban');
INSERT INTO genome_mapping(name) VALUES ('Talky');
INSERT INTO genome_mapping(name) VALUES ('Profanity');
INSERT INTO genome_mapping(name) VALUES ('Sincere');
INSERT INTO genome_mapping(name) VALUES ('Sentimental');
INSERT INTO genome_mapping(name) VALUES ('Emotional');
INSERT INTO genome_mapping(name) VALUES ('Best Friends');
INSERT INTO genome_mapping(name) VALUES ('Gays and Lesbians');
INSERT INTO genome_mapping(name) VALUES ('Rebelliousness');
INSERT INTO genome_mapping(name) VALUES ('Gender');
INSERT INTO genome_mapping(name) VALUES ('Rebellion');
INSERT INTO genome_mapping(name) VALUES ('60s');
INSERT INTO genome_mapping(name) VALUES ('London');
INSERT INTO genome_mapping(name) VALUES ('Controversial');
INSERT INTO genome_mapping(name) VALUES ('Realism');
INSERT INTO genome_mapping(name) VALUES ('Rock');
INSERT INTO genome_mapping(name) VALUES ('Celebrity Culture');
INSERT INTO genome_mapping(name) VALUES ('Drug Abuse');
INSERT INTO genome_mapping(name) VALUES ('Womanizer');
INSERT INTO genome_mapping(name) VALUES ('Going Straight');
INSERT INTO genome_mapping(name) VALUES ('Starting Over');
INSERT INTO genome_mapping(name) VALUES ('Friends');
INSERT INTO genome_mapping(name) VALUES ('Biography');
INSERT INTO genome_mapping(name) VALUES ('Independent');
INSERT INTO genome_mapping(name) VALUES ('50s');
INSERT INTO genome_mapping(name) VALUES ('70s');
INSERT INTO genome_mapping(name) VALUES ('Nightclub');
INSERT INTO genome_mapping(name) VALUES ('Touching');
INSERT INTO genome_mapping(name) VALUES ('Terminal Illness');
INSERT INTO genome_mapping(name) VALUES ('Unfulfillment');
INSERT INTO genome_mapping(name) VALUES ('Jazz');
INSERT INTO genome_mapping(name) VALUES ('Couples');
INSERT INTO genome_mapping(name) VALUES ('Infidelity');
INSERT INTO genome_mapping(name) VALUES ('Teenage Life');
INSERT INTO genome_mapping(name) VALUES ('Love and Romance');
INSERT INTO genome_mapping(name) VALUES ('Hospital');
INSERT INTO genome_mapping(name) VALUES ('Girls'' Night');
INSERT INTO genome_mapping(name) VALUES ('Disorder');
INSERT INTO genome_mapping(name) VALUES ('Denmark');
INSERT INTO genome_mapping(name) VALUES ('Not Serious');
INSERT INTO genome_mapping(name) VALUES ('Opposites Attract');
INSERT INTO genome_mapping(name) VALUES ('Wooing');
INSERT INTO genome_mapping(name) VALUES ('Gambling');
INSERT INTO genome_mapping(name) VALUES ('Period');
INSERT INTO genome_mapping(name) VALUES ('Romance');
INSERT INTO genome_mapping(name) VALUES ('19th Century');
INSERT INTO genome_mapping(name) VALUES ('France');
INSERT INTO genome_mapping(name) VALUES ('Paris');
INSERT INTO genome_mapping(name) VALUES ('Date Night');
INSERT INTO genome_mapping(name) VALUES ('Based on Play');
INSERT INTO genome_mapping(name) VALUES ('Nudity');
INSERT INTO genome_mapping(name) VALUES ('Sexual Content');
INSERT INTO genome_mapping(name) VALUES ('Clever');
INSERT INTO genome_mapping(name) VALUES ('Offbeat');
INSERT INTO genome_mapping(name) VALUES ('Witty');
INSERT INTO genome_mapping(name) VALUES ('Stylized');
INSERT INTO genome_mapping(name) VALUES ('Down on Your Luck');
INSERT INTO genome_mapping(name) VALUES ('Life Turned Upside Down');
INSERT INTO genome_mapping(name) VALUES ('Breakout');
INSERT INTO genome_mapping(name) VALUES ('False Accusation');
INSERT INTO genome_mapping(name) VALUES ('Nothing Goes Right');
INSERT INTO genome_mapping(name) VALUES ('Fall in Love');
INSERT INTO genome_mapping(name) VALUES ('Finland');
INSERT INTO genome_mapping(name) VALUES ('Strong Sexual Content');
INSERT INTO genome_mapping(name) VALUES ('Sexual');
INSERT INTO genome_mapping(name) VALUES ('Mischievous Children');
INSERT INTO genome_mapping(name) VALUES ('Sexual Relations');
INSERT INTO genome_mapping(name) VALUES ('Fish Out of Water');
INSERT INTO genome_mapping(name) VALUES ('Gangsters');
INSERT INTO genome_mapping(name) VALUES ('Couple Relations');
INSERT INTO genome_mapping(name) VALUES ('Curses Spells and Rituals');
INSERT INTO genome_mapping(name) VALUES ('Workplace Situations');
INSERT INTO genome_mapping(name) VALUES ('Workplace');
INSERT INTO genome_mapping(name) VALUES ('California');
INSERT INTO genome_mapping(name) VALUES ('Hotel');
INSERT INTO genome_mapping(name) VALUES ('Dark Humor');
INSERT INTO genome_mapping(name) VALUES ('Ensemble Cast');
INSERT INTO genome_mapping(name) VALUES ('Multiple Stories');
INSERT INTO genome_mapping(name) VALUES ('Surreal');
INSERT INTO genome_mapping(name) VALUES ('Exciting');
INSERT INTO genome_mapping(name) VALUES ('Criminal''s Revenge');
INSERT INTO genome_mapping(name) VALUES ('Friendship');
INSERT INTO genome_mapping(name) VALUES ('Good Versus Evil');
INSERT INTO genome_mapping(name) VALUES ('Witnessing a Crime');
INSERT INTO genome_mapping(name) VALUES ('Chase');
INSERT INTO genome_mapping(name) VALUES ('Crime Gone Awry');
INSERT INTO genome_mapping(name) VALUES ('Suburban Life');
INSERT INTO genome_mapping(name) VALUES ('Suburbs');
INSERT INTO genome_mapping(name) VALUES ('Ghost');
INSERT INTO genome_mapping(name) VALUES ('Supernatural Ability');
INSERT INTO genome_mapping(name) VALUES ('Vigilantism');
INSERT INTO genome_mapping(name) VALUES ('Doctors and Patients');
INSERT INTO genome_mapping(name) VALUES ('Isolation');
INSERT INTO genome_mapping(name) VALUES ('Riddles and Clues');
INSERT INTO genome_mapping(name) VALUES ('Road Not Taken');
INSERT INTO genome_mapping(name) VALUES ('Canada');
INSERT INTO genome_mapping(name) VALUES ('Estate');
INSERT INTO genome_mapping(name) VALUES ('Semi Fantastic');
INSERT INTO genome_mapping(name) VALUES ('Redemption');
INSERT INTO genome_mapping(name) VALUES ('Frame Up');
INSERT INTO genome_mapping(name) VALUES ('Urban Ghetto Life');
INSERT INTO genome_mapping(name) VALUES ('Injustice');
INSERT INTO genome_mapping(name) VALUES ('Fighting the System');
INSERT INTO genome_mapping(name) VALUES ('Legal');
INSERT INTO genome_mapping(name) VALUES ('Protagonist as Suspect');
INSERT INTO genome_mapping(name) VALUES ('Courtroom Drama');
INSERT INTO genome_mapping(name) VALUES ('Racism');
INSERT INTO genome_mapping(name) VALUES ('Texas');
INSERT INTO genome_mapping(name) VALUES ('Urban Ghetto');
INSERT INTO genome_mapping(name) VALUES ('Biting');
INSERT INTO genome_mapping(name) VALUES ('Cynical');
INSERT INTO genome_mapping(name) VALUES ('Losing Virginity');
INSERT INTO genome_mapping(name) VALUES ('Media');
INSERT INTO genome_mapping(name) VALUES ('Youth');
INSERT INTO genome_mapping(name) VALUES ('Media Satire');
INSERT INTO genome_mapping(name) VALUES ('Voyeurism');
INSERT INTO genome_mapping(name) VALUES ('High School');
INSERT INTO genome_mapping(name) VALUES ('Undercover');
INSERT INTO genome_mapping(name) VALUES ('Game Show');
INSERT INTO genome_mapping(name) VALUES ('Reality');
INSERT INTO genome_mapping(name) VALUES ('Prizes');
INSERT INTO genome_mapping(name) VALUES ('Athlete''s Life');
INSERT INTO genome_mapping(name) VALUES ('Twins');
INSERT INTO genome_mapping(name) VALUES ('Contests and Competitions');
INSERT INTO genome_mapping(name) VALUES ('Coming of Age');
INSERT INTO genome_mapping(name) VALUES ('Sport');
INSERT INTO genome_mapping(name) VALUES ('University');
INSERT INTO genome_mapping(name) VALUES ('Voice Over');
INSERT INTO genome_mapping(name) VALUES ('Scary');
INSERT INTO genome_mapping(name) VALUES ('Losing-it Hero');
INSERT INTO genome_mapping(name) VALUES ('Writer''s Life');
INSERT INTO genome_mapping(name) VALUES ('Haunted By the Past');
INSERT INTO genome_mapping(name) VALUES ('Confined');
INSERT INTO genome_mapping(name) VALUES ('Indoors');
INSERT INTO genome_mapping(name) VALUES ('Adventurer');
INSERT INTO genome_mapping(name) VALUES ('Young Heroes');
INSERT INTO genome_mapping(name) VALUES ('Obsessive Quest');
INSERT INTO genome_mapping(name) VALUES ('Child in Danger');
INSERT INTO genome_mapping(name) VALUES ('Imaginary Kingdom');
INSERT INTO genome_mapping(name) VALUES ('Legends and Myths');
INSERT INTO genome_mapping(name) VALUES ('Orphan');
INSERT INTO genome_mapping(name) VALUES ('Investigation');
INSERT INTO genome_mapping(name) VALUES ('Memory Loss');
INSERT INTO genome_mapping(name) VALUES ('Missing Person');
INSERT INTO genome_mapping(name) VALUES ('Family');
INSERT INTO genome_mapping(name) VALUES ('Australia');
INSERT INTO genome_mapping(name) VALUES ('Family Outing');
INSERT INTO genome_mapping(name) VALUES ('Pre-Teens');
INSERT INTO genome_mapping(name) VALUES ('Sexy');
INSERT INTO genome_mapping(name) VALUES ('Goofy Hero');
INSERT INTO genome_mapping(name) VALUES ('Looking for Sex');
INSERT INTO genome_mapping(name) VALUES ('Teenage Love');
INSERT INTO genome_mapping(name) VALUES ('College Life');
INSERT INTO genome_mapping(name) VALUES ('Student Life');
INSERT INTO genome_mapping(name) VALUES ('Young Lovers');
INSERT INTO genome_mapping(name) VALUES ('Mind Game');
INSERT INTO genome_mapping(name) VALUES ('Love Triangle');
INSERT INTO genome_mapping(name) VALUES ('Unfulfilled Love');
INSERT INTO genome_mapping(name) VALUES ('Stoners');
INSERT INTO genome_mapping(name) VALUES ('College');
INSERT INTO genome_mapping(name) VALUES ('Grossout Humor');
INSERT INTO genome_mapping(name) VALUES ('Androids and Robots');
INSERT INTO genome_mapping(name) VALUES ('Experiment Gone Awry');
INSERT INTO genome_mapping(name) VALUES ('Technology Gone Awry');
INSERT INTO genome_mapping(name) VALUES ('Deadly Creature');
INSERT INTO genome_mapping(name) VALUES ('Odd Couple');
INSERT INTO genome_mapping(name) VALUES ('Serial Killer');
INSERT INTO genome_mapping(name) VALUES ('Slasher');
INSERT INTO genome_mapping(name) VALUES ('Zombie');
INSERT INTO genome_mapping(name) VALUES ('Missing Child');
INSERT INTO genome_mapping(name) VALUES ('Survival');
INSERT INTO genome_mapping(name) VALUES ('Violence Spree');
INSERT INTO genome_mapping(name) VALUES ('High School Life');
INSERT INTO genome_mapping(name) VALUES ('Plague');
INSERT INTO genome_mapping(name) VALUES ('Animation');
INSERT INTO genome_mapping(name) VALUES ('Clergy');
INSERT INTO genome_mapping(name) VALUES ('Ocean or Sea');
INSERT INTO genome_mapping(name) VALUES ('Prostitute');
INSERT INTO genome_mapping(name) VALUES ('Optimism');
INSERT INTO genome_mapping(name) VALUES ('Preschoolers');
INSERT INTO genome_mapping(name) VALUES ('Blockbuster');
INSERT INTO genome_mapping(name) VALUES ('Critically Acclaimed');
INSERT INTO genome_mapping(name) VALUES ('Oscar Winner');
INSERT INTO genome_mapping(name) VALUES ('Modern Classic');
INSERT INTO genome_mapping(name) VALUES ('Bus');
INSERT INTO genome_mapping(name) VALUES ('Mountains');
INSERT INTO genome_mapping(name) VALUES ('Hollywood Tone');
INSERT INTO genome_mapping(name) VALUES ('All Star Cast');
INSERT INTO genome_mapping(name) VALUES ('Gory');
INSERT INTO genome_mapping(name) VALUES ('Computer Animated');
INSERT INTO genome_mapping(name) VALUES ('Based on Comics');
INSERT INTO genome_mapping(name) VALUES ('Captivating');
INSERT INTO genome_mapping(name) VALUES ('Uplifting');
INSERT INTO genome_mapping(name) VALUES ('Bittersweet');
INSERT INTO genome_mapping(name) VALUES ('Mentally Challenged');
INSERT INTO genome_mapping(name) VALUES ('Human Spirit');
INSERT INTO genome_mapping(name) VALUES ('Americana');
INSERT INTO genome_mapping(name) VALUES ('Rise To the Top');
INSERT INTO genome_mapping(name) VALUES ('Tragic Love');
INSERT INTO genome_mapping(name) VALUES ('True Love');
INSERT INTO genome_mapping(name) VALUES ('Destiny');
INSERT INTO genome_mapping(name) VALUES ('Original');
INSERT INTO genome_mapping(name) VALUES ('Epic');
INSERT INTO genome_mapping(name) VALUES ('Crumbling Marriage');
INSERT INTO genome_mapping(name) VALUES ('Midlife Crisis');
INSERT INTO genome_mapping(name) VALUES ('Under the Surface');
INSERT INTO genome_mapping(name) VALUES ('Dull Life');
INSERT INTO genome_mapping(name) VALUES ('Essential');
INSERT INTO genome_mapping(name) VALUES ('Satire');
INSERT INTO genome_mapping(name) VALUES ('Tragicomedy');
INSERT INTO genome_mapping(name) VALUES ('Brief Nudity');
INSERT INTO genome_mapping(name) VALUES ('Drugs/Alcohol');
INSERT INTO genome_mapping(name) VALUES ('Special Agents');
INSERT INTO genome_mapping(name) VALUES ('Government Agency');
INSERT INTO genome_mapping(name) VALUES ('Stalking');
INSERT INTO genome_mapping(name) VALUES ('Conspiracies');
INSERT INTO genome_mapping(name) VALUES ('Political Corruption');
INSERT INTO genome_mapping(name) VALUES ('Journalism');
INSERT INTO genome_mapping(name) VALUES ('Political Unrest');
INSERT INTO genome_mapping(name) VALUES ('State Affairs');
INSERT INTO genome_mapping(name) VALUES ('Interracial Relations');
INSERT INTO genome_mapping(name) VALUES ('Discrimination');
INSERT INTO genome_mapping(name) VALUES ('Revolution');
INSERT INTO genome_mapping(name) VALUES ('Historical');
INSERT INTO genome_mapping(name) VALUES ('Africa');
INSERT INTO genome_mapping(name) VALUES ('South Africa');
INSERT INTO genome_mapping(name) VALUES ('Strong Violent Content');
INSERT INTO genome_mapping(name) VALUES ('Femme Fatale');
INSERT INTO genome_mapping(name) VALUES ('Aging');
INSERT INTO genome_mapping(name) VALUES ('Love Affair');
INSERT INTO genome_mapping(name) VALUES ('Battle of the Sexes');
INSERT INTO genome_mapping(name) VALUES ('Twentysomething Life');
INSERT INTO genome_mapping(name) VALUES ('Thirtysomething Life');
INSERT INTO genome_mapping(name) VALUES ('City Life');
INSERT INTO genome_mapping(name) VALUES ('Erotic');
INSERT INTO genome_mapping(name) VALUES ('Store');
INSERT INTO genome_mapping(name) VALUES ('Irreverent Humor');
INSERT INTO genome_mapping(name) VALUES ('Dry Humor');
INSERT INTO genome_mapping(name) VALUES ('Master Criminal');
INSERT INTO genome_mapping(name) VALUES ('Partners Against Crime');
INSERT INTO genome_mapping(name) VALUES ('Secret Agents');
INSERT INTO genome_mapping(name) VALUES ('Tough Law Enforcer');
INSERT INTO genome_mapping(name) VALUES ('Drug Dealing');
INSERT INTO genome_mapping(name) VALUES ('Terrorism');
INSERT INTO genome_mapping(name) VALUES ('Addiction');
INSERT INTO genome_mapping(name) VALUES ('Working Undercover');
INSERT INTO genome_mapping(name) VALUES ('Spain');
INSERT INTO genome_mapping(name) VALUES ('Los Angeles');
INSERT INTO genome_mapping(name) VALUES ('Actor''s Life');
INSERT INTO genome_mapping(name) VALUES ('TV Show');
INSERT INTO genome_mapping(name) VALUES ('Hollywood');
INSERT INTO genome_mapping(name) VALUES ('Strong Female Presence');
INSERT INTO genome_mapping(name) VALUES ('Mad Scientist');
INSERT INTO genome_mapping(name) VALUES ('Violent Content');
INSERT INTO genome_mapping(name) VALUES ('Reunion');
INSERT INTO genome_mapping(name) VALUES ('Coming Out');
INSERT INTO genome_mapping(name) VALUES ('Homecoming');
INSERT INTO genome_mapping(name) VALUES ('Lovers Reunited');
INSERT INTO genome_mapping(name) VALUES ('Arizona');
INSERT INTO genome_mapping(name) VALUES ('Desert');
INSERT INTO genome_mapping(name) VALUES ('Disturbing');
INSERT INTO genome_mapping(name) VALUES ('Psychopath');
INSERT INTO genome_mapping(name) VALUES ('Nonlinear');
INSERT INTO genome_mapping(name) VALUES ('Stand Up and Sketches');
INSERT INTO genome_mapping(name) VALUES ('Quebec');
INSERT INTO genome_mapping(name) VALUES ('Dangerous Animal');
INSERT INTO genome_mapping(name) VALUES ('Chaos and Mayhem');
INSERT INTO genome_mapping(name) VALUES ('In the Woods');
INSERT INTO genome_mapping(name) VALUES ('Obsession');
INSERT INTO genome_mapping(name) VALUES ('30s');
INSERT INTO genome_mapping(name) VALUES ('World War 2');
INSERT INTO genome_mapping(name) VALUES ('Blind Ambition');
INSERT INTO genome_mapping(name) VALUES ('Rise and Fall');
INSERT INTO genome_mapping(name) VALUES ('Uncover Truth');
INSERT INTO genome_mapping(name) VALUES ('20s');
INSERT INTO genome_mapping(name) VALUES ('Classic');
INSERT INTO genome_mapping(name) VALUES ('Groundbreaking');
INSERT INTO genome_mapping(name) VALUES ('Masterpiece');
INSERT INTO genome_mapping(name) VALUES ('Episodic');
INSERT INTO genome_mapping(name) VALUES ('Film in Film');
INSERT INTO genome_mapping(name) VALUES ('Tragic Hero');
INSERT INTO genome_mapping(name) VALUES ('Working Class');
INSERT INTO genome_mapping(name) VALUES ('Washington');
INSERT INTO genome_mapping(name) VALUES ('Melodrama');
INSERT INTO genome_mapping(name) VALUES ('Orchestral');
INSERT INTO genome_mapping(name) VALUES ('Alternative');
INSERT INTO genome_mapping(name) VALUES ('Mysterious Character');
INSERT INTO genome_mapping(name) VALUES ('Afterlife');
INSERT INTO genome_mapping(name) VALUES ('Death in the Family');
INSERT INTO genome_mapping(name) VALUES ('Dealing With Death');
INSERT INTO genome_mapping(name) VALUES ('Family in Danger');
INSERT INTO genome_mapping(name) VALUES ('Social Relations');
INSERT INTO genome_mapping(name) VALUES ('Mystery');
INSERT INTO genome_mapping(name) VALUES ('Master Villain');
INSERT INTO genome_mapping(name) VALUES ('Tough Heroes');
INSERT INTO genome_mapping(name) VALUES ('Future');
INSERT INTO genome_mapping(name) VALUES ('Futuristic');
INSERT INTO genome_mapping(name) VALUES ('Social Differences');
INSERT INTO genome_mapping(name) VALUES ('Man Versus Machine');
INSERT INTO genome_mapping(name) VALUES ('Idealism');
INSERT INTO genome_mapping(name) VALUES ('Rich and Poor');
INSERT INTO genome_mapping(name) VALUES ('Expressionism');
INSERT INTO genome_mapping(name) VALUES ('Silent');
INSERT INTO genome_mapping(name) VALUES ('Factory');
INSERT INTO genome_mapping(name) VALUES ('Special Effects');
INSERT INTO genome_mapping(name) VALUES ('Filmmaking');
INSERT INTO genome_mapping(name) VALUES ('Manipulations');
INSERT INTO genome_mapping(name) VALUES ('Dancer''s Life');
INSERT INTO genome_mapping(name) VALUES ('Computers and Web');
INSERT INTO genome_mapping(name) VALUES ('Weddings');
INSERT INTO genome_mapping(name) VALUES ('Disability');
INSERT INTO genome_mapping(name) VALUES ('Switzerland');
INSERT INTO genome_mapping(name) VALUES ('Train');
INSERT INTO genome_mapping(name) VALUES ('Corporate Crimes');
INSERT INTO genome_mapping(name) VALUES ('Politics');
INSERT INTO genome_mapping(name) VALUES ('Forces of Nature');
INSERT INTO genome_mapping(name) VALUES ('New Orleans');
INSERT INTO genome_mapping(name) VALUES ('Washington DC');
INSERT INTO genome_mapping(name) VALUES ('Car Chase');
INSERT INTO genome_mapping(name) VALUES ('Environmentalism');
INSERT INTO genome_mapping(name) VALUES ('Oklahoma');
INSERT INTO genome_mapping(name) VALUES ('Laboratory');
INSERT INTO genome_mapping(name) VALUES ('Assassination');
INSERT INTO genome_mapping(name) VALUES ('Battles');
INSERT INTO genome_mapping(name) VALUES ('Mini Series');
INSERT INTO genome_mapping(name) VALUES ('Mentally Unstable');
INSERT INTO genome_mapping(name) VALUES ('New Jersey');
INSERT INTO genome_mapping(name) VALUES ('San Francisco');
INSERT INTO genome_mapping(name) VALUES ('Golden Years');
INSERT INTO genome_mapping(name) VALUES ('Adoption');
INSERT INTO genome_mapping(name) VALUES ('Culture Clash');
INSERT INTO genome_mapping(name) VALUES ('New Delhi');
INSERT INTO genome_mapping(name) VALUES ('Mind Bending');
INSERT INTO genome_mapping(name) VALUES ('Private Detective');
INSERT INTO genome_mapping(name) VALUES ('Looking for Love');
INSERT INTO genome_mapping(name) VALUES ('Eccentric Family');
INSERT INTO genome_mapping(name) VALUES ('Family Gatherings');
INSERT INTO genome_mapping(name) VALUES ('Unlikely Couple');
INSERT INTO genome_mapping(name) VALUES ('Impossible Love');
INSERT INTO genome_mapping(name) VALUES ('Singleness');
INSERT INTO genome_mapping(name) VALUES ('Rhode Island');
INSERT INTO genome_mapping(name) VALUES ('Pirate');
INSERT INTO genome_mapping(name) VALUES ('18th Century');
INSERT INTO genome_mapping(name) VALUES ('Ship');
INSERT INTO genome_mapping(name) VALUES ('Caribbean');
INSERT INTO genome_mapping(name) VALUES ('Master Warrior');
INSERT INTO genome_mapping(name) VALUES ('One Man Army');
INSERT INTO genome_mapping(name) VALUES ('Uninhibited Rivalry');
INSERT INTO genome_mapping(name) VALUES ('Hitman');
INSERT INTO genome_mapping(name) VALUES ('Postmodernism');
INSERT INTO genome_mapping(name) VALUES ('Anti War');
INSERT INTO genome_mapping(name) VALUES ('Basic Training');
INSERT INTO genome_mapping(name) VALUES ('War');
INSERT INTO genome_mapping(name) VALUES ('Gulf War');
INSERT INTO genome_mapping(name) VALUES ('Iraq');
INSERT INTO genome_mapping(name) VALUES ('Middle East');
INSERT INTO genome_mapping(name) VALUES ('Battle Zone');
INSERT INTO genome_mapping(name) VALUES ('Immigrants');
INSERT INTO genome_mapping(name) VALUES ('Germany');
INSERT INTO genome_mapping(name) VALUES ('Mutant');
INSERT INTO genome_mapping(name) VALUES ('Vampire');
INSERT INTO genome_mapping(name) VALUES ('School');
INSERT INTO genome_mapping(name) VALUES ('Campy');
INSERT INTO genome_mapping(name) VALUES ('Michigan');
INSERT INTO genome_mapping(name) VALUES ('Bar');
INSERT INTO genome_mapping(name) VALUES ('Remake');
INSERT INTO genome_mapping(name) VALUES ('Submarine');
INSERT INTO genome_mapping(name) VALUES ('Underwater');
INSERT INTO genome_mapping(name) VALUES ('Babies and Infants');
INSERT INTO genome_mapping(name) VALUES ('Family Life');
INSERT INTO genome_mapping(name) VALUES ('Office');
INSERT INTO genome_mapping(name) VALUES ('Forbidden Love');
INSERT INTO genome_mapping(name) VALUES ('Dangerous Attraction');
INSERT INTO genome_mapping(name) VALUES ('Fugitives');
INSERT INTO genome_mapping(name) VALUES ('Cinderella Story');
INSERT INTO genome_mapping(name) VALUES ('Royal Family');
INSERT INTO genome_mapping(name) VALUES ('Head of State');
INSERT INTO genome_mapping(name) VALUES ('Misfit Partners');
INSERT INTO genome_mapping(name) VALUES ('Prank');
INSERT INTO genome_mapping(name) VALUES ('Cross Country');
INSERT INTO genome_mapping(name) VALUES ('Slapstick');
INSERT INTO genome_mapping(name) VALUES ('Workplace Romance');
INSERT INTO genome_mapping(name) VALUES ('Social Misfits');
INSERT INTO genome_mapping(name) VALUES ('Animal life');
INSERT INTO genome_mapping(name) VALUES ('Prehistory');
INSERT INTO genome_mapping(name) VALUES ('Jungle');
INSERT INTO genome_mapping(name) VALUES ('When the Parents Are Away');
INSERT INTO genome_mapping(name) VALUES ('Beach');
INSERT INTO genome_mapping(name) VALUES ('Israel');
INSERT INTO genome_mapping(name) VALUES ('Antarctica');
INSERT INTO genome_mapping(name) VALUES ('Vietnam War');
INSERT INTO genome_mapping(name) VALUES ('Vietnam');
INSERT INTO genome_mapping(name) VALUES ('Cambodia');
INSERT INTO genome_mapping(name) VALUES ('Fighting Crime');
INSERT INTO genome_mapping(name) VALUES ('Prodigy');
INSERT INTO genome_mapping(name) VALUES ('Superhero');
INSERT INTO genome_mapping(name) VALUES ('Supernatural Romance');
INSERT INTO genome_mapping(name) VALUES ('Leadership');
INSERT INTO genome_mapping(name) VALUES ('Daring Rescue');
INSERT INTO genome_mapping(name) VALUES ('Ancient History');
INSERT INTO genome_mapping(name) VALUES ('Mexico');
INSERT INTO genome_mapping(name) VALUES ('Latin America');
INSERT INTO genome_mapping(name) VALUES ('Saga');
INSERT INTO genome_mapping(name) VALUES ('Nightlife');
INSERT INTO genome_mapping(name) VALUES ('Unsupportive Spouse');
INSERT INTO genome_mapping(name) VALUES ('Elderly');
INSERT INTO genome_mapping(name) VALUES ('Hostages');
INSERT INTO genome_mapping(name) VALUES ('Split Personality');
INSERT INTO genome_mapping(name) VALUES ('Digital Video');
INSERT INTO genome_mapping(name) VALUES ('Mummy');
INSERT INTO genome_mapping(name) VALUES ('Moral Dilemma');
INSERT INTO genome_mapping(name) VALUES ('Master and Servant');
INSERT INTO genome_mapping(name) VALUES ('World Spanning');
INSERT INTO genome_mapping(name) VALUES ('Farce');
INSERT INTO genome_mapping(name) VALUES ('Treasure Hunt');
INSERT INTO genome_mapping(name) VALUES ('Reincarnation');
INSERT INTO genome_mapping(name) VALUES ('Egypt');
INSERT INTO genome_mapping(name) VALUES ('Single Parent');
INSERT INTO genome_mapping(name) VALUES ('Alcohol Abuse');
INSERT INTO genome_mapping(name) VALUES ('Unemployment');
INSERT INTO genome_mapping(name) VALUES ('Lebanon');
INSERT INTO genome_mapping(name) VALUES ('Western');
INSERT INTO genome_mapping(name) VALUES ('Old West');
INSERT INTO genome_mapping(name) VALUES ('Wyoming');
INSERT INTO genome_mapping(name) VALUES ('Political Conspiracy');
INSERT INTO genome_mapping(name) VALUES ('Righting the Wronged');
INSERT INTO genome_mapping(name) VALUES ('Alaska');
INSERT INTO genome_mapping(name) VALUES ('Pets');
INSERT INTO genome_mapping(name) VALUES ('Tennessee');
INSERT INTO genome_mapping(name) VALUES ('Village Life');
INSERT INTO genome_mapping(name) VALUES ('Getting Home');
INSERT INTO genome_mapping(name) VALUES ('Ireland');
INSERT INTO genome_mapping(name) VALUES ('Village');
INSERT INTO genome_mapping(name) VALUES ('Fashion');
INSERT INTO genome_mapping(name) VALUES ('Military Base');
INSERT INTO genome_mapping(name) VALUES ('Hit TV Series');
INSERT INTO genome_mapping(name) VALUES ('Sitcom');
INSERT INTO genome_mapping(name) VALUES ('Reluctant Partners');
INSERT INTO genome_mapping(name) VALUES ('Manhunt');
INSERT INTO genome_mapping(name) VALUES ('Police Corruption');
INSERT INTO genome_mapping(name) VALUES ('Captivity');
INSERT INTO genome_mapping(name) VALUES ('Kenya');
INSERT INTO genome_mapping(name) VALUES ('Against the Rules');
INSERT INTO genome_mapping(name) VALUES ('Family Business');
INSERT INTO genome_mapping(name) VALUES ('Pakistan');
INSERT INTO genome_mapping(name) VALUES ('Elevator');
INSERT INTO genome_mapping(name) VALUES ('Forgery');
INSERT INTO genome_mapping(name) VALUES ('Madrid');
INSERT INTO genome_mapping(name) VALUES ('Museum');
INSERT INTO genome_mapping(name) VALUES ('Hotshot Hero');
INSERT INTO genome_mapping(name) VALUES ('Restaurant');
INSERT INTO genome_mapping(name) VALUES ('Sexual Abuse');
INSERT INTO genome_mapping(name) VALUES ('Kids in Trouble');
INSERT INTO genome_mapping(name) VALUES ('Transvestism');
INSERT INTO genome_mapping(name) VALUES ('Island');
INSERT INTO genome_mapping(name) VALUES ('Custody');
INSERT INTO genome_mapping(name) VALUES ('Wilderness');
INSERT INTO genome_mapping(name) VALUES ('Skyscraper');
INSERT INTO genome_mapping(name) VALUES ('Twists and Turns');
INSERT INTO genome_mapping(name) VALUES ('Hidden Identity');
INSERT INTO genome_mapping(name) VALUES ('Indiana');
INSERT INTO genome_mapping(name) VALUES ('Outer Space');
INSERT INTO genome_mapping(name) VALUES ('Space Station');
INSERT INTO genome_mapping(name) VALUES ('Spacecraft');
INSERT INTO genome_mapping(name) VALUES ('Cult');
INSERT INTO genome_mapping(name) VALUES ('Based on Short Story');
INSERT INTO genome_mapping(name) VALUES ('Classical');
INSERT INTO genome_mapping(name) VALUES ('Golden Globe Winner');
INSERT INTO genome_mapping(name) VALUES ('Artist''s Life');
INSERT INTO genome_mapping(name) VALUES ('Experimental');
INSERT INTO genome_mapping(name) VALUES ('Secret Identity');
INSERT INTO genome_mapping(name) VALUES ('Espionage');
INSERT INTO genome_mapping(name) VALUES ('Emmy Winner');
INSERT INTO genome_mapping(name) VALUES ('Teaching the Ways of the World');
INSERT INTO genome_mapping(name) VALUES ('Scotland');
INSERT INTO genome_mapping(name) VALUES ('Mental Illness');
INSERT INTO genome_mapping(name) VALUES ('Clinic');
INSERT INTO genome_mapping(name) VALUES ('Punk');
INSERT INTO genome_mapping(name) VALUES ('Nanny');
INSERT INTO genome_mapping(name) VALUES ('Philadelphia');
INSERT INTO genome_mapping(name) VALUES ('Rising To Stardom');
INSERT INTO genome_mapping(name) VALUES ('Relationship Vs Career');
INSERT INTO genome_mapping(name) VALUES ('Desire for Fame');
INSERT INTO genome_mapping(name) VALUES ('Mississippi');
INSERT INTO genome_mapping(name) VALUES ('Underdog');
INSERT INTO genome_mapping(name) VALUES ('Detroit');
INSERT INTO genome_mapping(name) VALUES ('Hip Hop');
INSERT INTO genome_mapping(name) VALUES ('Neo Noir');
INSERT INTO genome_mapping(name) VALUES ('Palestinian Authority');
INSERT INTO genome_mapping(name) VALUES ('Arkansas');
INSERT INTO genome_mapping(name) VALUES ('Memphis');
INSERT INTO genome_mapping(name) VALUES ('Country');
INSERT INTO genome_mapping(name) VALUES ('Folk');
INSERT INTO genome_mapping(name) VALUES ('Partly B&amp;W');
INSERT INTO genome_mapping(name) VALUES ('Hardcase Students');
INSERT INTO genome_mapping(name) VALUES ('Teachers and Students');
INSERT INTO genome_mapping(name) VALUES ('Adolescence Vs Adulthood');
INSERT INTO genome_mapping(name) VALUES ('Wizards and Magicians');
INSERT INTO genome_mapping(name) VALUES ('Cafe');
INSERT INTO genome_mapping(name) VALUES ('Singapore');
INSERT INTO genome_mapping(name) VALUES ('Kansas');
INSERT INTO genome_mapping(name) VALUES ('Resort');
INSERT INTO genome_mapping(name) VALUES ('Feminism');
INSERT INTO genome_mapping(name) VALUES ('New Zealand');
INSERT INTO genome_mapping(name) VALUES ('Haunted House');
INSERT INTO genome_mapping(name) VALUES ('Athlete and Trainer');
INSERT INTO genome_mapping(name) VALUES ('Dance School');
INSERT INTO genome_mapping(name) VALUES ('Parody');
INSERT INTO genome_mapping(name) VALUES ('Las Vegas');
INSERT INTO genome_mapping(name) VALUES ('Casino');
INSERT INTO genome_mapping(name) VALUES ('Superhuman Powers');
INSERT INTO genome_mapping(name) VALUES ('Based on Film');
INSERT INTO genome_mapping(name) VALUES ('Based on Folk Tale');
INSERT INTO genome_mapping(name) VALUES ('Wartime Life');
INSERT INTO genome_mapping(name) VALUES ('Religions or Cults');
INSERT INTO genome_mapping(name) VALUES ('Blaxploitation');
INSERT INTO genome_mapping(name) VALUES ('Boss and Employee');
INSERT INTO genome_mapping(name) VALUES ('Workplace Intrigue');
INSERT INTO genome_mapping(name) VALUES ('Obnoxious Boss');
INSERT INTO genome_mapping(name) VALUES ('Italy');
INSERT INTO genome_mapping(name) VALUES ('Berlin Festival Winner');
INSERT INTO genome_mapping(name) VALUES ('Breakup');
INSERT INTO genome_mapping(name) VALUES ('Austria');
INSERT INTO genome_mapping(name) VALUES ('Amateur Detective');
INSERT INTO genome_mapping(name) VALUES ('Sundance Festival Winner');
INSERT INTO genome_mapping(name) VALUES ('Lone Wolves');
INSERT INTO genome_mapping(name) VALUES ('Changing the Past or Future');
INSERT INTO genome_mapping(name) VALUES ('South Dakota');
INSERT INTO genome_mapping(name) VALUES ('Countryside');
INSERT INTO genome_mapping(name) VALUES ('New Mexico');
INSERT INTO genome_mapping(name) VALUES ('Ego Clash');
INSERT INTO genome_mapping(name) VALUES ('Theater');
INSERT INTO genome_mapping(name) VALUES ('Dedicated Lawyer');
INSERT INTO genome_mapping(name) VALUES ('Price of Justice');
INSERT INTO genome_mapping(name) VALUES ('Hijacking');
INSERT INTO genome_mapping(name) VALUES ('Airplane');
INSERT INTO genome_mapping(name) VALUES ('Legal Action');
INSERT INTO genome_mapping(name) VALUES ('Archive Footage');
INSERT INTO genome_mapping(name) VALUES ('Anime');
INSERT INTO genome_mapping(name) VALUES ('Middle Ages');
INSERT INTO genome_mapping(name) VALUES ('Miami');
INSERT INTO genome_mapping(name) VALUES ('Sexual Harassment');
INSERT INTO genome_mapping(name) VALUES ('Parallel World');
INSERT INTO genome_mapping(name) VALUES ('Gender Bending');
INSERT INTO genome_mapping(name) VALUES ('Campaign');
INSERT INTO genome_mapping(name) VALUES ('Inventions and Discoveries');
INSERT INTO genome_mapping(name) VALUES ('Peru');
INSERT INTO genome_mapping(name) VALUES ('Samurai');
INSERT INTO genome_mapping(name) VALUES ('Soul');
INSERT INTO genome_mapping(name) VALUES ('Rehabilitation');
INSERT INTO genome_mapping(name) VALUES ('Mental Institution');
INSERT INTO genome_mapping(name) VALUES ('Brazil');
INSERT INTO genome_mapping(name) VALUES ('Courtroom');
INSERT INTO genome_mapping(name) VALUES ('Comedy of Errors');
INSERT INTO genome_mapping(name) VALUES ('Holland');
INSERT INTO genome_mapping(name) VALUES ('Convent');
INSERT INTO genome_mapping(name) VALUES ('1910s');
INSERT INTO genome_mapping(name) VALUES ('Beverly Hills');
INSERT INTO genome_mapping(name) VALUES ('Verbal Byplay');
INSERT INTO genome_mapping(name) VALUES ('Highly Acclaimed Short');
INSERT INTO genome_mapping(name) VALUES ('Farm');
INSERT INTO genome_mapping(name) VALUES ('Downfall');
INSERT INTO genome_mapping(name) VALUES ('Cause and Meaning');
INSERT INTO genome_mapping(name) VALUES ('Legal Investigation');
INSERT INTO genome_mapping(name) VALUES ('Venice Festival Winner');
INSERT INTO genome_mapping(name) VALUES ('Unlikely Partners');
INSERT INTO genome_mapping(name) VALUES ('Boston');
INSERT INTO genome_mapping(name) VALUES ('Prison Life');
INSERT INTO genome_mapping(name) VALUES ('Wrongfully Committed');
INSERT INTO genome_mapping(name) VALUES ('Florida');
INSERT INTO genome_mapping(name) VALUES ('Innocence Lost');
INSERT INTO genome_mapping(name) VALUES ('Hawaii');
INSERT INTO genome_mapping(name) VALUES ('Cuba');
INSERT INTO genome_mapping(name) VALUES ('Latin');
INSERT INTO genome_mapping(name) VALUES ('Oregon');
INSERT INTO genome_mapping(name) VALUES ('Animation &amp; Live Action');
INSERT INTO genome_mapping(name) VALUES ('Corrupt Ruler');
INSERT INTO genome_mapping(name) VALUES ('Intrigue');
INSERT INTO genome_mapping(name) VALUES ('Roman Empire');
INSERT INTO genome_mapping(name) VALUES ('Transsexual');
INSERT INTO genome_mapping(name) VALUES ('Barcelona');
INSERT INTO genome_mapping(name) VALUES ('R&amp;B');
INSERT INTO genome_mapping(name) VALUES ('Murderous Pair');
INSERT INTO genome_mapping(name) VALUES ('Nigeria');
INSERT INTO genome_mapping(name) VALUES ('Political Intrigue');
INSERT INTO genome_mapping(name) VALUES ('Church');
INSERT INTO genome_mapping(name) VALUES ('Assassination Attempt');
INSERT INTO genome_mapping(name) VALUES ('Who Done It');
INSERT INTO genome_mapping(name) VALUES ('Destructive Relationship');
INSERT INTO genome_mapping(name) VALUES ('Hungary');
INSERT INTO genome_mapping(name) VALUES ('Cooking and Food');
INSERT INTO genome_mapping(name) VALUES ('Save the Planet');
INSERT INTO genome_mapping(name) VALUES ('Supportive Spouse');
INSERT INTO genome_mapping(name) VALUES ('Dogma');
INSERT INTO genome_mapping(name) VALUES ('Taxi');
INSERT INTO genome_mapping(name) VALUES ('Korea');
INSERT INTO genome_mapping(name) VALUES ('Anti Semitism');
INSERT INTO genome_mapping(name) VALUES ('Former Yugoslavia');
INSERT INTO genome_mapping(name) VALUES ('Boarding School Life');
INSERT INTO genome_mapping(name) VALUES ('Boarding School');
INSERT INTO genome_mapping(name) VALUES ('Palaces Castles and Temples');
INSERT INTO genome_mapping(name) VALUES ('Circus');
INSERT INTO genome_mapping(name) VALUES ('Stand Alone');
INSERT INTO genome_mapping(name) VALUES ('Massachusetts');
INSERT INTO genome_mapping(name) VALUES ('Campus');
INSERT INTO genome_mapping(name) VALUES ('Fairytale');
INSERT INTO genome_mapping(name) VALUES ('Mercy Killing');
INSERT INTO genome_mapping(name) VALUES ('Thailand');
INSERT INTO genome_mapping(name) VALUES ('Against Humanity');
INSERT INTO genome_mapping(name) VALUES ('Romania');
INSERT INTO genome_mapping(name) VALUES ('Hong Kong');
INSERT INTO genome_mapping(name) VALUES ('Chicago');
INSERT INTO genome_mapping(name) VALUES ('Based on TV Series');
INSERT INTO genome_mapping(name) VALUES ('Unlikely criminals');
INSERT INTO genome_mapping(name) VALUES ('Mars');
INSERT INTO genome_mapping(name) VALUES ('Bank');
INSERT INTO genome_mapping(name) VALUES ('Poland');
INSERT INTO genome_mapping(name) VALUES ('Domestic Disturbance');
INSERT INTO genome_mapping(name) VALUES ('Louisiana');
INSERT INTO genome_mapping(name) VALUES ('Japan');
INSERT INTO genome_mapping(name) VALUES ('Theme Park');
INSERT INTO genome_mapping(name) VALUES ('Dedicated Educator');
INSERT INTO genome_mapping(name) VALUES ('Juvenile Delinquency');
INSERT INTO genome_mapping(name) VALUES ('Pennsylvania');
INSERT INTO genome_mapping(name) VALUES ('Gothic');
INSERT INTO genome_mapping(name) VALUES ('World');
INSERT INTO genome_mapping(name) VALUES ('Virginia');
INSERT INTO genome_mapping(name) VALUES ('World War 1');
INSERT INTO genome_mapping(name) VALUES ('Colombia');
INSERT INTO genome_mapping(name) VALUES ('Wish Come True');
INSERT INTO genome_mapping(name) VALUES ('Show Tunes');
INSERT INTO genome_mapping(name) VALUES ('Sport Team');
INSERT INTO genome_mapping(name) VALUES ('Fascism');
INSERT INTO genome_mapping(name) VALUES ('Monastery');
INSERT INTO genome_mapping(name) VALUES ('New Wave');
INSERT INTO genome_mapping(name) VALUES ('Mute or Deaf');
INSERT INTO genome_mapping(name) VALUES ('Tokyo');
INSERT INTO genome_mapping(name) VALUES ('Seattle');
INSERT INTO genome_mapping(name) VALUES ('Sweden');
INSERT INTO genome_mapping(name) VALUES ('Belgium');
INSERT INTO genome_mapping(name) VALUES ('Ghent');
INSERT INTO genome_mapping(name) VALUES ('Heavy Metal');
INSERT INTO genome_mapping(name) VALUES ('Amsterdam');
INSERT INTO genome_mapping(name) VALUES ('Rome');
INSERT INTO genome_mapping(name) VALUES ('Switching Roles');
INSERT INTO genome_mapping(name) VALUES ('Space Wars');
INSERT INTO genome_mapping(name) VALUES ('Camp');
INSERT INTO genome_mapping(name) VALUES ('Greece');
INSERT INTO genome_mapping(name) VALUES ('Chile');
INSERT INTO genome_mapping(name) VALUES ('Based on Short Film');
INSERT INTO genome_mapping(name) VALUES ('Screwball');
INSERT INTO genome_mapping(name) VALUES ('Nevada');
INSERT INTO genome_mapping(name) VALUES ('Afghanistan');
INSERT INTO genome_mapping(name) VALUES ('Dystopia');
INSERT INTO genome_mapping(name) VALUES ('3D');
INSERT INTO genome_mapping(name) VALUES ('Mockumentary');
INSERT INTO genome_mapping(name) VALUES ('Folk Hero');
INSERT INTO genome_mapping(name) VALUES ('Soap Opera');
INSERT INTO genome_mapping(name) VALUES ('Holocaust');
INSERT INTO genome_mapping(name) VALUES ('Miraculous Event');
INSERT INTO genome_mapping(name) VALUES ('Nature');
INSERT INTO genome_mapping(name) VALUES ('Distant Planet');
INSERT INTO genome_mapping(name) VALUES ('American Civil War');
INSERT INTO genome_mapping(name) VALUES ('Genocide');
INSERT INTO genome_mapping(name) VALUES ('Rwanda');
INSERT INTO genome_mapping(name) VALUES ('New England');
INSERT INTO genome_mapping(name) VALUES ('Vermont');
INSERT INTO genome_mapping(name) VALUES ('Fake Documentary');
INSERT INTO genome_mapping(name) VALUES ('Sicily');
INSERT INTO genome_mapping(name) VALUES ('Illinois');
INSERT INTO genome_mapping(name) VALUES ('Variety and Entertainment');
INSERT INTO genome_mapping(name) VALUES ('Magazine');
INSERT INTO genome_mapping(name) VALUES ('Interviews');
INSERT INTO genome_mapping(name) VALUES ('Child Illness');
INSERT INTO genome_mapping(name) VALUES ('Airport');
INSERT INTO genome_mapping(name) VALUES ('Nebraska');
INSERT INTO genome_mapping(name) VALUES ('Physical Appearance');
INSERT INTO genome_mapping(name) VALUES ('Arms Dealing');
INSERT INTO genome_mapping(name) VALUES ('Jamaica');
INSERT INTO genome_mapping(name) VALUES ('Mine');
INSERT INTO genome_mapping(name) VALUES ('Georgia');
INSERT INTO genome_mapping(name) VALUES ('Elderly Lovers');
INSERT INTO genome_mapping(name) VALUES ('Stop Motion');
INSERT INTO genome_mapping(name) VALUES ('1900s');
INSERT INTO genome_mapping(name) VALUES ('Victorian');
INSERT INTO genome_mapping(name) VALUES ('Officers and Cadets');
INSERT INTO genome_mapping(name) VALUES ('Connecticut');
INSERT INTO genome_mapping(name) VALUES ('Maine');
INSERT INTO genome_mapping(name) VALUES ('Settlement');
INSERT INTO genome_mapping(name) VALUES ('Montana');
INSERT INTO genome_mapping(name) VALUES ('Arts and Culture');
INSERT INTO genome_mapping(name) VALUES ('Celebrity guests');
INSERT INTO genome_mapping(name) VALUES ('Maryland');
INSERT INTO genome_mapping(name) VALUES ('Venice');
INSERT INTO genome_mapping(name) VALUES ('Minnesota');
INSERT INTO genome_mapping(name) VALUES ('Royal Court');
INSERT INTO genome_mapping(name) VALUES ('North Carolina');
INSERT INTO genome_mapping(name) VALUES ('Morocco');
INSERT INTO genome_mapping(name) VALUES ('Surfing');
INSERT INTO genome_mapping(name) VALUES ('Czech Republic');
INSERT INTO genome_mapping(name) VALUES ('Lake or River');
INSERT INTO genome_mapping(name) VALUES ('Puerto Rico');
INSERT INTO genome_mapping(name) VALUES ('Rio De Janeiro');
INSERT INTO genome_mapping(name) VALUES ('Car Race');
INSERT INTO genome_mapping(name) VALUES ('Bosnia');
INSERT INTO genome_mapping(name) VALUES ('Business and Finance');
INSERT INTO genome_mapping(name) VALUES ('Voting or Send-Off');
INSERT INTO genome_mapping(name) VALUES ('Multiple Contestants');
INSERT INTO genome_mapping(name) VALUES ('Unscripted');
INSERT INTO genome_mapping(name) VALUES ('Hosted');
INSERT INTO genome_mapping(name) VALUES ('Continuous');
INSERT INTO genome_mapping(name) VALUES ('Retirement Home ');
INSERT INTO genome_mapping(name) VALUES ('Utah');
INSERT INTO genome_mapping(name) VALUES ('Spaghetti Western');
INSERT INTO genome_mapping(name) VALUES ('Death Row');
INSERT INTO genome_mapping(name) VALUES ('Shopping Mall');
INSERT INTO genome_mapping(name) VALUES ('Ukraine');
INSERT INTO genome_mapping(name) VALUES ('16th Century');
INSERT INTO genome_mapping(name) VALUES ('Army Investigation');
INSERT INTO genome_mapping(name) VALUES ('Colorado');
INSERT INTO genome_mapping(name) VALUES ('Turkey');
INSERT INTO genome_mapping(name) VALUES ('17th Century');
INSERT INTO genome_mapping(name) VALUES ('Brussels');
INSERT INTO genome_mapping(name) VALUES ('French Riviera');
INSERT INTO genome_mapping(name) VALUES ('Pittsburgh');
INSERT INTO genome_mapping(name) VALUES ('15th Century');
INSERT INTO genome_mapping(name) VALUES ('Portugal');
INSERT INTO genome_mapping(name) VALUES ('Iran');
INSERT INTO genome_mapping(name) VALUES ('Neo realism');
INSERT INTO genome_mapping(name) VALUES ('Ethiopia');
INSERT INTO genome_mapping(name) VALUES ('Libya');
INSERT INTO genome_mapping(name) VALUES ('Ghetto');
INSERT INTO genome_mapping(name) VALUES ('Concentration Camp');
INSERT INTO genome_mapping(name) VALUES ('Blues');
INSERT INTO genome_mapping(name) VALUES ('Wrestling');
INSERT INTO genome_mapping(name) VALUES ('Baltimore');
INSERT INTO genome_mapping(name) VALUES ('Stadium');
INSERT INTO genome_mapping(name) VALUES ('Radio Show');
INSERT INTO genome_mapping(name) VALUES ('Ancient Mystery');
INSERT INTO genome_mapping(name) VALUES ('Syria');
INSERT INTO genome_mapping(name) VALUES ('Kentucky');
INSERT INTO genome_mapping(name) VALUES ('Ohio');
INSERT INTO genome_mapping(name) VALUES ('Tuscany');
INSERT INTO genome_mapping(name) VALUES ('Harlem');
INSERT INTO genome_mapping(name) VALUES ('Oldies');
INSERT INTO genome_mapping(name) VALUES ('Puppets');
INSERT INTO genome_mapping(name) VALUES ('Moon');
INSERT INTO genome_mapping(name) VALUES ('Control Room');
INSERT INTO genome_mapping(name) VALUES ('Missouri');
INSERT INTO genome_mapping(name) VALUES ('Hidden Cameras');
INSERT INTO genome_mapping(name) VALUES ('Prague');
INSERT INTO genome_mapping(name) VALUES ('Travel and Leisure');
INSERT INTO genome_mapping(name) VALUES ('Diner');
INSERT INTO genome_mapping(name) VALUES ('Disco');
INSERT INTO genome_mapping(name) VALUES ('D Day');
INSERT INTO genome_mapping(name) VALUES ('New Hampshire');
INSERT INTO genome_mapping(name) VALUES ('Battleship');
INSERT INTO genome_mapping(name) VALUES ('Skiing');
INSERT INTO genome_mapping(name) VALUES ('Investigative');
INSERT INTO genome_mapping(name) VALUES ('Based on Video Game');
INSERT INTO genome_mapping(name) VALUES ('Wisconsin');
INSERT INTO genome_mapping(name) VALUES ('Bahamas');
INSERT INTO genome_mapping(name) VALUES ('Argentina');
INSERT INTO genome_mapping(name) VALUES ('Holy Land');
INSERT INTO genome_mapping(name) VALUES ('Opera');
INSERT INTO genome_mapping(name) VALUES ('Based on Article');
INSERT INTO genome_mapping(name) VALUES ('Police Station');
INSERT INTO genome_mapping(name) VALUES ('South Carolina');
INSERT INTO genome_mapping(name) VALUES ('Bolivia');
INSERT INTO genome_mapping(name) VALUES ('Web Series');
INSERT INTO genome_mapping(name) VALUES ('Iowa');
INSERT INTO genome_mapping(name) VALUES ('Seaport');
INSERT INTO genome_mapping(name) VALUES ('Movie Set');
INSERT INTO genome_mapping(name) VALUES ('Kindergarten');
INSERT INTO genome_mapping(name) VALUES ('Ordinary people');
INSERT INTO genome_mapping(name) VALUES ('Baseball');
INSERT INTO genome_mapping(name) VALUES ('Hotshot Lawyer');
INSERT INTO genome_mapping(name) VALUES ('Toddlers');
INSERT INTO genome_mapping(name) VALUES ('Culinary');
INSERT INTO genome_mapping(name) VALUES ('Retirement Home Life');
INSERT INTO genome_mapping(name) VALUES ('Burma');
INSERT INTO genome_mapping(name) VALUES ('Somalia');
INSERT INTO genome_mapping(name) VALUES ('Science and Technology');
INSERT INTO genome_mapping(name) VALUES ('Delaware');
INSERT INTO genome_mapping(name) VALUES ('Reggae');
INSERT INTO genome_mapping(name) VALUES ('Macedonia');
INSERT INTO genome_mapping(name) VALUES ('Topical');
INSERT INTO genome_mapping(name) VALUES ('Taiwan');
INSERT INTO genome_mapping(name) VALUES ('Ecuador');
INSERT INTO genome_mapping(name) VALUES ('Child as Adult');
INSERT INTO genome_mapping(name) VALUES ('Indonesia');
INSERT INTO genome_mapping(name) VALUES ('Elementary School');
INSERT INTO genome_mapping(name) VALUES ('Gas Station');
INSERT INTO genome_mapping(name) VALUES ('Uruguay');
INSERT INTO genome_mapping(name) VALUES ('Luck');
INSERT INTO genome_mapping(name) VALUES ('Studio');
INSERT INTO genome_mapping(name) VALUES ('Timed Answer or Time Limit');
INSERT INTO genome_mapping(name) VALUES ('Tibet');
INSERT INTO genome_mapping(name) VALUES ('Attic');
INSERT INTO genome_mapping(name) VALUES ('Beauty Salon');
INSERT INTO genome_mapping(name) VALUES ('Talk Show');
INSERT INTO genome_mapping(name) VALUES ('Mongolia');
INSERT INTO genome_mapping(name) VALUES ('Malaysia');
INSERT INTO genome_mapping(name) VALUES ('Iceland');
INSERT INTO genome_mapping(name) VALUES ('Seoul');
INSERT INTO genome_mapping(name) VALUES ('Idaho');
INSERT INTO genome_mapping(name) VALUES ('Health and Fitness');
INSERT INTO genome_mapping(name) VALUES ('Lifestyle');
INSERT INTO genome_mapping(name) VALUES ('Tips');
INSERT INTO genome_mapping(name) VALUES ('Stories (articles)');
INSERT INTO genome_mapping(name) VALUES ('Kazakhstan');
INSERT INTO genome_mapping(name) VALUES ('Slovakia');
INSERT INTO genome_mapping(name) VALUES ('News');
INSERT INTO genome_mapping(name) VALUES ('Uganda');
INSERT INTO genome_mapping(name) VALUES ('Norway');
INSERT INTO genome_mapping(name) VALUES ('Medical School');
INSERT INTO genome_mapping(name) VALUES ('The Philippines');
INSERT INTO genome_mapping(name) VALUES ('Florence');
INSERT INTO genome_mapping(name) VALUES ('North Dakota');
INSERT INTO genome_mapping(name) VALUES ('Jordan');
INSERT INTO genome_mapping(name) VALUES ('Georgia (Former USSR)');
INSERT INTO genome_mapping(name) VALUES ('Trivia');
INSERT INTO genome_mapping(name) VALUES ('Quiz');
INSERT INTO genome_mapping(name) VALUES ('Tunnel');
INSERT INTO genome_mapping(name) VALUES ('Saudi Arabia');
INSERT INTO genome_mapping(name) VALUES ('Wine and Alcohol');
INSERT INTO genome_mapping(name) VALUES ('Nicaragua');
INSERT INTO genome_mapping(name) VALUES ('Consumerism');
INSERT INTO genome_mapping(name) VALUES ('Antwerp');
INSERT INTO genome_mapping(name) VALUES ('Home and Garden');
INSERT INTO genome_mapping(name) VALUES ('Algeria');
INSERT INTO genome_mapping(name) VALUES ('Venezuela');
INSERT INTO genome_mapping(name) VALUES ('Haiti');
INSERT INTO genome_mapping(name) VALUES ('Medical');
INSERT INTO genome_mapping(name) VALUES ('Congo');
INSERT INTO genome_mapping(name) VALUES ('Cavern');
INSERT INTO genome_mapping(name) VALUES ('White House');
INSERT INTO genome_mapping(name) VALUES ('Motor');
INSERT INTO genome_mapping(name) VALUES ('Motion Capture');
INSERT INTO genome_mapping(name) VALUES ('Dungeon');
INSERT INTO genome_mapping(name) VALUES ('Co-Hosting');
INSERT INTO genome_mapping(name) VALUES ('Panel');
INSERT INTO genome_mapping(name) VALUES ('West Virginia');
INSERT INTO genome_mapping(name) VALUES ('Extreme Sport');
INSERT INTO genome_mapping(name) VALUES ('Albania');
INSERT INTO genome_mapping(name) VALUES ('Football');
INSERT INTO genome_mapping(name) VALUES ('Kids');
INSERT INTO genome_mapping(name) VALUES ('Educational');
INSERT INTO genome_mapping(name) VALUES ('Sudan');
INSERT INTO genome_mapping(name) VALUES ('Bulgaria');
INSERT INTO genome_mapping(name) VALUES ('Swimming');
INSERT INTO genome_mapping(name) VALUES ('Serbia');
INSERT INTO genome_mapping(name) VALUES ('Hockey');
INSERT INTO genome_mapping(name) VALUES ('Nepal');
INSERT INTO genome_mapping(name) VALUES ('Basketball');
INSERT INTO genome_mapping(name) VALUES ('Latvia');
INSERT INTO genome_mapping(name) VALUES ('Costa Rica');
INSERT INTO genome_mapping(name) VALUES ('How To');
INSERT INTO genome_mapping(name) VALUES ('Travelogue');
INSERT INTO genome_mapping(name) VALUES ('Paraguay');
INSERT INTO genome_mapping(name) VALUES ('Zimbabwe');
INSERT INTO genome_mapping(name) VALUES ('Cycling');
INSERT INTO genome_mapping(name) VALUES ('Soccer');
INSERT INTO genome_mapping(name) VALUES ('Puzzles');
INSERT INTO genome_mapping(name) VALUES ('Wordplay');
INSERT INTO genome_mapping(name) VALUES ('Compound');
INSERT INTO genome_mapping(name) VALUES ('Tunisia');
INSERT INTO genome_mapping(name) VALUES ('Live');
INSERT INTO genome_mapping(name) VALUES ('Based on Web');
INSERT INTO genome_mapping(name) VALUES ('Texting Emailing or Chatting');
INSERT INTO genome_mapping(name) VALUES ('Debate');
INSERT INTO genome_mapping(name) VALUES ('Investments');
INSERT INTO genome_mapping(name) VALUES ('Trading');
INSERT INTO genome_mapping(name) VALUES ('Home Improvement');
INSERT INTO genome_mapping(name) VALUES ('Interior Design');
INSERT INTO genome_mapping(name) VALUES ('Bruges');
INSERT INTO genome_mapping(name) VALUES ('Late Night');
INSERT INTO genome_mapping(name) VALUES ('Croatia');
INSERT INTO genome_mapping(name) VALUES ('Boxing');
INSERT INTO genome_mapping(name) VALUES ('Skating');
INSERT INTO genome_mapping(name) VALUES ('Estonia');
INSERT INTO genome_mapping(name) VALUES ('Morning Show');
INSERT INTO genome_mapping(name) VALUES ('Weather');
INSERT INTO genome_mapping(name) VALUES ('Motorcycle Race');
INSERT INTO genome_mapping(name) VALUES ('Skill');
INSERT INTO genome_mapping(name) VALUES ('Kosovo');
INSERT INTO genome_mapping(name) VALUES ('Tasks');
INSERT INTO genome_mapping(name) VALUES ('Montenegro');
INSERT INTO genome_mapping(name) VALUES ('Slovenia');
INSERT INTO genome_mapping(name) VALUES ('Advice');
INSERT INTO genome_mapping(name) VALUES ('Summer School');
INSERT INTO genome_mapping(name) VALUES ('Boardgame');
INSERT INTO genome_mapping(name) VALUES ('Telenovela');
INSERT INTO genome_mapping(name) VALUES ('Interactive');
