CREATE TABLE `STAGING_IMDB_MOVIES` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(256) DEFAULT NULL,
  `imdbId` VARCHAR(256) DEFAULT NULL,
  `url` VARCHAR(256) DEFAULT NULL,
  PRIMARY KEY (`id`)
);
